openapi: 3.0.2
info:
  title: Samnordisk runtextdatabas söktjänst API
  description: Samnordisk runtextdatabas (SRD) söktjänst API. Specification för Riksantikvarieämbetets
    forskningsplattform för runor inom projektet Evighetsrunor. API:et används för
    att hitta och söka i runtexter i SRD. Sökresultaten innehåller endast grundinformationen
    om runtexterna (id:n, text och geografiska koordinater). Ytterligare metadata
    runt runtexterna, bärarobjekt samt kopplad information hämtas via K-SAMSÖK
  contact:
    url: https://www.raa.se/kulturarv/runor-och-runstenar/projektet-evighetsrunor/
  version: 0.9.7
servers:
  - description: Uppsala Universitet Evighetsrunor API - TEST
    url: http://runor.test.uu.se/rest/
#  - description: SwaggerHub API Auto Mocking

### Generella implementationsregler i API:et ###
# Regel 1: Arrayer har alltid ett värde.
#  Dvs om ett en array saknar värde så har den noll elemement. Effekten blir att en array kan aldrig ha värdet null.
# Regel 2: Ingående objekt (subobjekt) i en respons har alltid ett värde.
# Dvs om responsen innehåller ett subobjekt "provenance" så är objektet alltid definierat. Subobjekt kan aldrig ha värdet null.

## Angående hur vi tolkar required och nullable ##
# Regel 3: Tolkning av required: Attributet ingår alltid i responseobjektet, oavsett om attributet har ett värde eller ej.
# Specifikation för "required" i ett schemaobject: https://swagger.io/specification/#schemaObject
# Regel 4: Tolkning av nullable: Om ett attribut är deklarerat med värdet Nullable: false så innebär det att attributet alltid förväntas innehålla ett värde.
# Om nullable däremot är true - då ingår alltid variablen i responsen men kan ha värdet null.
# Ex: {"period": null, ...}"
# Defaultvärdet för nullable är false. Så om en variabel inte är deklarerad med "nullable" innebär det att den får värdet false.
# Specifikation för "nullable" i ett schemaobject:  https://swagger.io/specification/#schemaNullable

#### Utestående frågor #####
# Sök efter TODO i detta dokument. Där finns en utestående fråga.

paths:
  /signa:
    get:
      tags:
        - Enkel sökning
      summary: Hämtar lista med signum och dess kopplade runinskrifters identiteter.
      description: |
        Hämtar en lista med signum  och dess kopplade runinskrifts identitet (uuid). <br>
        Lämpligt att användas för typeahead ändamål vid sökning/hämtning av signum. <br>
        Notera att minst 2 tecken måste anges för att sökningen ska utföras. <br>
        Sökträffar sorteras i fallande bokstavsordning enligt naturligt språk för en runforskare. Se responseobjekt för exempel.
      parameters:
        - name: edition_id
          in: query
          description: Anger id för önskad utgåva.
          required: true
          schema:
            type: string
            example: 2020
        - name: matching_text
          in: query
          description: Anger initala tecken i de signum som eftersöks. Case insensitive, dvs "Öl" eller "öl" ger samma sökresultat.
          schema:
            type: string
            minLength: 2
            example: "U "
      responses:
        200:
          description: |
            En sorterad lista med signum returneras. <br>
            Signumen sorteras i fallande bokstavsordning enligt naturligt språk för en runforskare. <br>
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Signum'
                example:
                  - Öl 1: ccf0a7f9-1f4c-...
                  - Öl 2: ccf0a7f9-1f4c-...
                  - Öl 2b: ccf0a7f9-1f4c-...
                  - Öl 10: ccf0a7f9-1f4c-...
                  - Öl ANF1937;184: ccf0a7f9-...
                  - Öl ANF1937;185: ccf0a7f9-...
        400:
          description: (Bad request). Felaktigt indata angavs till tjänsten (typiskt valideringsfel).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: (Not found). Inga poster hittades.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /places:
    get:
      tags:
        - Enkel sökning
      summary: Hämtar lista med places (platser) och identiteter till runinskrifter som är kopplade till platsen.
      description: |
        Hämtar lista med places (platser) och de identiteter till runinskrifter som är kopplade till platsen. <br>
        Lämpligt att användas för typeahead ändamål vid sökning/hämtning av signum. <br>
        Notera att minst 2 tecken måste anges för att sökningen ska utföras. <br>
        Sökträffar sorteras i fallande bokstavsordning.
      parameters:
        - name: edition_id
          in: query
          description: Anger id för önskad utgåva.
          required: true
          schema:
            type: string
            example: 2020
        - name: matching_text
          in: query
          description: Anger initiala tecken i namnet på plats som eftersöks. Case insensitive, dvs "bor" eller "Bor" ger samma sökresultat.
          schema:
            type: string
            minLength: 2
            example: "Resmo "
      responses:
        200:
          description: |
            En sorterad lista med namn på platser returneras. <br>
            Platserna sorteras i fallande bokstavsordning.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PlaceResponse'
                example:
                  - Resmo: ccf0a7f9-1f4c-...
                  - Resmo kyrka: ccf0a7f9-1f4c-...
        400:
          description: (Bad request). Felaktigt indata angavs till tjänsten (typiskt valideringsfel).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: (Not found). Inga poster hittades.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /selection/groups:
    get:
      tags:
        - Avancerad sökning
      summary: Hämtar lista med urvalsgrupper
      description: Hämtar lista med urvalsgrupper att användas när man sätter filtervillkor för en avancerad sökning.
        Dessa används sedan som input till exempelvis tjänsten /selection/groups/{group_id} mfl.
      parameters:
        - name: edition_id
          in: query
          description: Id för önskad utgåva
          required: true
          schema:
            type: string
      responses:
        200:
          description: En lista med urvalsgrupper
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                #  $ref: '#/components/schemas/SelectionGroup'
                example: "[LAND, LANDSKAP, HARAD, SOCKEN, LAN, KOMMUN, FOREMAL, RUNOLOGISK_PERIOD, PROFILSTIL, RISTARE, BRAKTEATYP]"
        400:
          description: (Bad request). Felaktigt indata angavs till tjänsten (typiskt valideringsfel).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /selection/groups/{group_id}:
    get:
      tags:
        - Avancerad sökning
      summary: Hämtar lista med urval
      description: Hämtar lista med urval för en urvalsgrupp att användas när man
        sätter filtervillkor för en avancerad sökning
      parameters:
        - name: edition_id
          in: query
          description: Id för önskad utgåva
          required: true
          schema:
            type: string
        - name: group_id
          in: path
          description: Id för urvalsgrupp.
          required: true
          schema:
            type: string
            example: 'LAND, LANDSKAP, SOCKEN, ..., RUNOLOGISK_PERIOD, RAK, INGULV, A'
        - name: matching_text
          in: query
          description: Anger initiala tecken i del av namn på urval som eftersöks. Case insensitive, dvs "bor" eller "Bor" ger samma sökresultat.
          schema:
            type: string
            minLength: 2
            example: "Sve"
      responses:
        200:
          description: En lista med urval.
          content:
            application/json:
              schema:
                type: array
                example:
                  - id: ca79d466-888f-4011-b5bd-35fc6dd1d622
                    name: Sverige
                    has_children: false
                  - id: 25a4de16-c421-41ed-8d17-fc465fd03db1
                    name: Bok
                    has_children: false
                  - id: b70ec612-cef6-446d-afc0-4e3387804858
                    name: 'Urnordisk/vikingatid'
                    has_children: false
                  - id: c95ec612-cef6-446d-afc0-4e3387804752
                    name: 'RAK'
                    has_children: false
                  - id: b70ec612-cef6-446d-afc0-4e3387804842
                    name: '...'
                    has_children: false
                items:
                  $ref: '#/components/schemas/SelectionItem'
        400:
          description: (Bad request). Felaktigt indata angavs till tjänsten (typiskt valideringsfel).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: (Not found). Gruppen saknas.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: 404
                message: Gruppen saknas
                path: /selection/12/test
                timestamp: 1990-12-31T23:59:60Z
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /selection/groups/{group_id}/{subgroup_id}:
    get:
      tags:
        - Avancerad sökning
      summary: Hämtar lista med urval där både grupp och subgrupp kan anges.
      description: Hämtar lista med urval för en urvalsgrupp att användas när man
        sätter filtervillkor för en avancerad sökning TODO
      parameters:
        - name: edition_id
          in: query
          description: Id för önskad utgåva
          required: true
          schema:
            type: string
        - name: group_id
          in: path
          description: Id för urvalsgrupp.
          required: true
          schema:
            type: string
            example: 'MATERIALTYP, KORSFORM'
        - name: subgroup_id
          in: path
          description: Anger subgroupId för urvalsgruppen.
          required: true
          schema:
            type: string
            example: 'BEN/HORN, METALL, STEN, ... A ,B , C, ...'
        - name: matching_text
          in: query
          description: Anger initiala tecken i del av namn på urval som eftersöks. Case insensitive, dvs "bor" eller "Bor" ger samma sökresultat.
          schema:
            type: string
            minLength: 1
            example: "Ben/H"
      responses:
        200:
          description: En lista med urval.
          content:
            application/json:
              schema:
                type: array
                example:
                  - id: ca79d466-888f-4011-b5bd-35fc6dd1d622
                    name: Sverige
                  - id: 25a4de16-c421-41ed-8d17-fc465fd03db1
                    name: Bok
                  - id: b70ec612-cef6-446d-afc0-4e3387804858
                    name: 'Urnordisk/vikingatid'
                  - id: c95ec612-cef6-446d-afc0-4e3387804752
                    name: 'RAK'
                  - id: b70ec612-cef6-446d-afc0-4e3387804842
                    name: '...'
                items:
                  $ref: '#/components/schemas/SelectionItem'
        400:
          description: (Bad request). Felaktigt indata angavs till tjänsten (typiskt valideringsfel).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: (Not found). Gruppen saknas.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: 404
                message: Gruppen saknas
                path: /selection/12/test
                timestamp: 1990-12-31T23:59:60Z
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /translationtypes:
    get:
      tags:
        - Avancerad sökning
      summary: Hämtar alla möjliga översättningstyper som en sökning kan göras utifrån.
      description: Översättningstyper att använda när en sökfråga sätts samman
      parameters:
        - name: edition_id
          in: query
          description: Id för önskad utgåva
          required: true
          schema:
            type: string
      responses:
        200:
          description: (OK)
          content:
            application/json:
              schema:
                type: array
                example:
                  - id: da0b20c8-e036-456b-8f0a-6aeb06105f9a
                    name: Fornvästnordiska
                    proper_name_searchable: true
                    is_complete: true
                    method: NORMALISERING
                  - id: ca79d466-888f-4011-b5bd-35fc6dd1d623
                    name: Engelska
                    proper_name_searchable: false
                    is_complete: false
                    method: OVERSATTNING
                items:
                  $ref: '#/components/schemas/RunicTextTranslationType'
        400:
          description: (Bad request). Felaktigt indata angavs till tjänsten (typiskt valideringsfel).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /search:
    get:
      tags:
        - Enkel sökning
      summary: Enkel sökning. Sök efter runinskrifter med platsnamn eller signum.
      description: |
        Enkel sökning. Sök efter runinskrifter med platsnamn eller signum. <br>
        Om inga sökresultat hittades returneras en tom array. <br>
        Sökresultat sorteras i fallande bokstavsordning enligt naturligt språk. <br>
        Exempel 1: Öl 1, Öl 2, Öl 10. <br>
        Exempel 2: Ög 35, Ög 36, Ög 36B, Ög 37, Ög. <br>
        Exempel 3: .... Ög 247, Ög 248, Ög ANF1937;184, Ög ANF1937;185 .... <br>
      parameters:
        - name: edition_id
          in: query
          description: Id för önskad utgåva
          required: true
          schema:
            type: string
            example: "2020"
        - name: matching_text
          in: query
          description: Söksträng
          required: true
          schema:
            type: string
            example: "'Resmo kyrka' eller 'Öl 10'"
        - name: search_field
          in: query
          description: Sökfält
          required: true
          schema:
            type: string
            enum:
              - PLACE
              - SIGNUM
      responses:
        200:
          description: (OK)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RunicInscriptionIndex'
        400:
          description: (Bad request). Felaktigt indata angavs till tjänsten (typiskt valideringsfel).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Avancerad sökning
      summary: Avancerad sökning i runtexter enligt sökvillkor
      description: Sök i runtexter enligt kombinerade sökvillkor för text samt filtrering
        enligt urval
      parameters:
        - name: edition_id
          in: path
          description: Id för önskad utgåva
          required: true
          schema:
            type: string
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/SearchQuery'
        required: true
      responses:
        200:
          description: Hittade runtexter med markering av hittade ord
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SearchResult'
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
      x-codegen-request-body-name: query
  /map:
    get:
      tags:
        - Karta
      summary: Hämtar alla geografiska punkter
      description: Hämtar alla geografiska punkter där runinskriptioner finns eller
        har hittats
      parameters:
        - name: edition_id
          in: query
          description: Id för önskad utgåva
          required: true
          schema:
            type: string
        - name: bbox
          in: query
          description: |
            Anger koordinater i kommaseparerad lista för spatial utsökning i bboxformat; left,top,bottom,right.
            Exempel 688232.203,6332689.351,713304.203,6345041.351 Koordinatsystem för geometrier förväntas vara WGS84 (EPSG:4326).
          required: true
          schema:
            type: string
      responses:
        200:
          description: (OK). Poster hittades.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MapIndex'
        400:
          description: (Bad request). Felaktigt indata angavs till tjänsten (typiskt valideringsfel).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /inscriptions:
    get:
      tags:
        - Runtexter
        - Not implemented
      summary: Hämtar en lista med runinskrifter.
      description: Hämtar en lista med runinskrifter för en viss utgåva
      parameters:
        - name: edition_id
          in: query
          description: Id för önskad utgåva
          required: true
          schema:
            type: string
            example: 2020
        - name: inscription_id
          in: query
          description: |
            Anger ev. identitet/er (uuid) för runinskrifter som ska hämtas.
          schema:
            type: array
            items:
              type: string
              format: uuid
              example:
                - ccf0a7f9-1f4c-421f-a321-0e36daea43eb, cfc0a7f9-1f4c-421f-a321-0e36daea56be
        - name: page
          in: query
          description: Index för önskad resultatsida
          schema:
            type: number
            format: number
        - name: size
          in: query
          description: Storlek på sidor
          schema:
            type: number
            format: number
        - name: sort
          in: query
          description: Attribut som man vill använda föra att sortera svaret, tex "sort=id",
            eller "sort=id,desc" om man vill ha svaret i fallande ordning.
          schema:
            type: string
            format: sort
      responses:
        200:
          description: (OK). Posten hittades.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedRunicInscriptionResponse'
        400:
          description: (Bad request). Felaktigt indata angavs till tjänsten (typiskt valideringsfel).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /inscriptions/{id}:
    get:
      tags:
        - Runtexter
      summary: Hämtar en runinskrift med hjälp av uuid.
      description: Hämtar en runinskrift med hjälp av uuid.
      parameters:
        - in: path
          name: id
          description: Anger identiteten till inskriften (uuid).
          required: true
          schema:
            type: string
            format: uuid
        - name: edition_id
          in: query
          description: Id för önskad utgåva
          required: true
          schema:
            type: string
      responses:
        200:
          description: (OK). Post hittades
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunicInscription'
        404:
          description: (Not found). Ingen träff
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: 404
                message: Signum eller URI saknas
                path: /selection/12/test
                timestamp: 1990-12-31T23:59:60Z
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /editions:
    get:
      tags:
        - Utgåva
      summary: Hämtar en lista med utgåvor
      description: Hämtar en lista med utgåvor
      responses:
        200:
          description: (OK). Poster hittades
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Edition'
        404:
          description: (Not found). Ingen träff
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                status: 404
                message: Utgåvor saknas
                path: /editions
                timestamp: 2001-12-31T23:59:60Z
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /editions/{edition_id}/download:
    get:
      tags:
        - Utgåva
        - Not implemented
      summary: Hämtar all data i en utgåva
      description: 'Hämtar en fil som innehåller all data i en utgåva av SRD. TODO bestämma vilket format som returneras.'
      parameters:
        - name: edition_id
          in: path
          description: Id för önskad utgåva
          required: true
          schema:
            type: string
      responses:
        200:
          description: (OK). Poster hittades
          content: {}
        404:
          description: (Not found). Ingen träff
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/Error'
            application/json:
              example:
                status: 404
                message: Utgåva saknas
                path: /editions/1987
                timestamp: 2018-12-31T23:59:60Z
        500:
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/Error'

  /echo/{message}:
    get:
      summary: Tjänst avsedd för att utföra sambandstest. Tjänsten returnerar det argument soma angavs som inparameter i anropet.
      parameters:
        - in: path
          name: message
          description: Värdet för det 'eko' som ska returneras tillbaka till klienten.
          required: true
          schema:
            type: string
            example: "Hurra! Anropet lyckades."
      responses:
        '200':
          description: (OK). Ett json-objekt med attributet 'echo' returneras.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Echo'
        '500':
          description: (Internal server error). Ett oväntat fel inträffade.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - Övriga tjänster
components:
  schemas:
    Cross:
      type: object
      description: Objektrepresentation av ett kors. Beskriver hur korsets olika delar ser ut enligt ett schema skapat av Linn Lager.
      properties:
        cross_forms:
          type: array
          items:
            $ref: '#/components/schemas/CrossForm'

    CrossForm:
      type: object
      description: JSON-representation av korsformer. Beskriver hur korsets olika delar ser ut enligt ett schema skapat av Linn Lager.
      properties:
        aspect:
          description: Anger raden - dvs "versalen" för en korsform. Korsets övergripande form.
          type: string
          example:
            C
        form:
          description: Anger kolumnen - dvs "siffran" för en korsform. Anger hur delen av ett kors ser ut.
          type: string
          example:
            3

    Echo:
      type: object
      description: Objekt för att representera svaret till echo-tjänsten.
      properties:
        echo:
          description: Anger värdet som som skickades in till tjänsten.
          type: string
          example: Hurra! Tjänsten svarar. Anropet lyckades.
    Edition:
      required:
        - id
      type: object
      properties:
        id:
          type: string
          description: Identitet på utgåvan
          example: "2018"
        name:
          type: string
          description: Namn på utgåvan
          example: 2018 års utgåva av Samnordisk runtextdatabas
        latest:
          type: boolean
          description: Anger om utgåvan är den aktuella (senast utgivna)
          example: true
        download:
          type: string
          description: Anger URL för att ladda ner all data i en utgåva
          example: /editions/2018/download
      description: En utgåva (version) av SRD

    Error:
      required:
        - message
        - path
        - status
        - timestamp
      type: object
      properties:
        status:
          type: integer
          description: Http statuskod
          example: 500
        message:
          type: string
          description: Innehåller ett felmeddelande tänkt att presenteras för slutanvändare
          example: Tekniskt fel, försök senare
        exception:
          type: string
          description: Innehåller ett felmeddelande tänkt för tekniker vid felsökning
          example: java.lang.NullPointerException
        path:
          type: string
          description: Anger den resourcepath där felet uppstod
          example: /selection/13/Test
        timestamp:
          type: string
          description: Anger tidpunkten när felet inträffade. Tidpunkt angiven som
            date-time, se RFC3339 (Internet Date/Time Format)
          format: dateTime
          example: 2019-01-04T23:59:60Z
      description: Ett fel

    Geometry:
      type: object
      description: |
        Objektrepresentation av en geografisk position uttryckt enligt GeoJSON[2016] specificatioenen. Se https://tools.ietf.org/html/rfc7946.
        Notera att koordinatsystemet för angivna koordinater är uttryckta i WGS84 (EPSG:4326). Se: https://tools.ietf.org/html/rfc7946#section-4
        "The coordinate reference system for all GeoJSON coordinates is a geographic coordinate reference system, using the World Geodetic System 1984 (WGS 84) [WGS84] datum,
        with longitude and latitude units of decimal degrees.
        This is equivalent to the coordinate reference system identified by the Open Geospatial Consortium (OGC) URN urn:ogc:def:crs:OGC::CRS84."
      properties:
        type:
          description: Anger tillåtna koordinattyper för geometrin.
          type: string
          enum:
            - Point
          example: Point
        coordinates:
          description: |
            Anger koordinater för geometrin. Exemplet uttryckt enligt longitude, latitude.
            Se: https://tools.ietf.org/html/rfc7946#appendix-A.1
            "Point coordinates are in x, y order (easting, northing for projected coordinates, longitude, and latitude for geographic coordinates)".
          type: array
          items:
            type: number
            example: "18.31511, 57.159624"

    Interpretation:
      type: object
      description: Objektrepresentation av en Interpretation (transliterering).
      properties:
        text:
          description: Anger transliterering av en text
          type: string
          nullable: true
          example: Bengt lät resa denna sten efter sin moder...  (på fornnordiska)
        language:
          type: string
          nullable: true
          description: Anger språket som translitterering är uttryckt i.
          example: Fornvästnordiska.

    Nmr:
      type: object
      description: Objektrepresentation av National Monument Registers (NMR) identifierare kopplade till inskriftsbäraren i andra informationssystem.
      properties:
        country:
          description: Anger vilket land de kopplade NMR-identiteterna tillhör.
            Danmark, Skottland, Norge, Sverige
          type: string
          enum:
            - dk
            - gb_sc
            - "no" # Use quotes to avoid parsing no as false. https://github.com/swagger-api/swagger-parser/issues/1205
            - se
          example: se
        identifiers:
          description: Array över nmr-identiteter.
          type: array
          items:
            $ref: '#/components/schemas/NmrIdentifier'

    NmrIdentifier:
      type: object
      description: Objektrepresentation av en nyckel-värde par för en nmr-identifiere.
      properties:
        key:
          description: Anger typen av nmr-identitet.
          type: string
          example: fmisid
        value:
          description: Anger värdet för nmr-identiteten.
          type: string
          example: abc123

    Material:
      type: object
      required:
        - material
        - materialtype
      description: Objektrepresentation av en materialförekomst för inskriftsbärare.
      properties:
        material:
          description: Anger det material som inskriftsbäraren består av.
          type: string
          example: granit
        material_type:
          description: Anger typen i form av grov indelning av det material som inskriftsbäraren består av.
          type: string
          example: sten

    PagedRunicInscriptionResponse:
      type: object
      properties:
        content:
          type: array
          description: Runinskrifter
          items:
            $ref: '#/components/schemas/RunicInscription'
        total_pages:
          type: integer
          description: Totalt antal sidor som kan hämtas
          example: 84
        total_elements:
          type: integer
          description: Totalt antal objekt som kan hämtas
          example: 8345
        last:
          type: boolean
          description: Anger om aktuell sida är den sista
          example: false
        sort:
          type: string
          description: Anger vilken sortering som använts
          example: sort=id
        first:
          type: boolean
          description: Anger om aktuell sida är den första
          example: true
        number_of_elements:
          type: integer
          description: Antal objekt i aktuellt svar
          example: 100
        size:
          type: integer
          description: Anger antal objekt per sida
          example: 100
        number:
          type: integer
          description: Sidnummer
          example: 0
      description: Paginerat svar med runinskription

    ProfileStyle:
      description: Objektrepresentation som anger med vilken profilstil som inskriftsbäraren är ristad. Används bara om inskriftsbäraren är en runsten.
      type: object
      properties:
        style:
          description: Anger med vilken profilstil som inskriftsbäraren är ristad.
          type: string
          example: Pr3
        certainty:
          description: Anger säkerhetsfaktorn för bedömningen. "Det här är definitivt profilstil 2"
          type: boolean
          example: true

    Provenance:
      type: object
      description: Objektrepresentation av en runinskrifts lokaliseringsinformation.
      properties:
        place:
          description: Anger platsen för var inskriftsbäraren ursprungligen kommer från.
          type: string
          example: Resmo kyrka
        parish:
          description: Anger ev. namn på socken där inskriftsbäraren hittades.
          type: string
          nullable: true
          example: Bro socken
        old_parish:
          description: Anger ev. tidigare namn på socken där inskriftsbäraren hittades.
          type: string
          nullable: true
          example: Bro socken
        hundred:
          description: Anger ev. namn på härad där inskriftsbäraren hittades.
          type: string
          nullable: true
          example: Vallentuna hd
        province:
          description: Anger ev. namn på landskap där inskriftsbäraren hittades.
          type: string
          nullable: true
          example: Västra götaland
        county:
          description: Anger ev. namn på län där inskriftsbäraren hittades.
          type: string
          nullable: true
          example: Gotland
        municipality:
          description: Anger ev. namn på kommun där inskriftsbäraren hittades.
          type: string
          nullable: true
          example: Rättvik
        country:
          description: Anger ev. namn på land där inskriftsbäraren hittades.
          type: string
          nullable: true
          example: Sverige

    OriginalLocation:
      description: Grundinformation om en inskriftsbärares ursprungliga placering.
      type: object
      properties:
        original:
          description: Beskriver om inskriftsbäraren har kvar sin ursprungliga placering eller ej.
            Notera att värdet är trinärt! Dvs det kan anta tre värden. False, true respektive null.
            Null innebär att värdet är okänt.
          type: boolean
          nullable: true
          example: false
        text:
          description: Anger ev. beskrivningstext för inskriftsbärarens ursprungliga placering.
          type: string
          nullable: true
          example: "200 m sydöst om nuvarande position."

    # TODO - Överväg byt namn - lär finnas på wikin. Marcus återkommer.
    RunicInscription:
      description: Grundinformation för en runinskription.
      type: object
      properties:
        inscription_id:
          type: string
          format: uuid
          description: Anger identiteten (uuid) till runinskriften.
          example: ccf0a7f9-1f4c-421f-a321-0e36daea43eb
        uri:
          description: Persistent identifierare för det sammansatta objektet (runinskrift + bärare av runinskriften) (används för att hämta information från K-SAMSÖK)
          type: string
          example: http://kulturarvsdata.se/uu/srdb/7b70c89a-c191-4d73-4455fd5dd2a7
        signum1:
          description: Anger den första identitetsdelen för runinskriften, s.k signum.
            Platsbaserad. Oftast landskapskoden där runstenen hittades. Sätts samman med attribut 'signum 2'
          type: string
          example: Öl
        signum2:
          description: Anger den andra identitetssdelen för runinskriften, s.k signum.
            Anger oftast runinskriftens numrering inom platsbaserade delen. Sätts samman med attribut 'signum 1'
          type: string
          example: 10
        alternative_signa:
          description: Alternativa signa.
          type: array
          items:
            type: string
          example:
            - Liljegren 1588
            - Liljegren 1589
            - BN 4
        extant:
          description: Anger om inskriftsbäraren existerar eller ej.
          type: boolean
          example: true
        placement:
          description: Anger var inskriftsbäraren finns belägen.
          type: string
          nullable: true
          example: Kalmar läns museum (KLM 24962)
        original_location:
          $ref: '#/components/schemas/OriginalLocation'
        position:
          # Anger geografisk information om inskriftsbärarens position.
          $ref: '#/components/schemas/RunicInscriptionGeoPosition'
        provenance:
          $ref: '#/components/schemas/Provenance'
        crosses:
          description: Array av kors.
          type: array
          items:
            $ref: '#/components/schemas/Cross'
        artefact:
          description: Anger vilken typ av föremål inskriftsbäraren är av.
          nullable: true
          type: string
          example: runsten
        runic_types:
          description: Anger vilka typer av runor som använts i inskriften.
          type: array
          items:
            $ref: '#/components/schemas/RunicType'
        runic_type_descriptions:
          description: Anger fritextbeskrivningar av de typer av runor som använts i inskriften.
          type: array
          items:
            $ref: '#/components/schemas/RunicTypeDescription'
        period:
          description: Anger vilken konvention som använts vid skapandet av läsningen av inskriften.
            Är i praktiken även en grov tidsangivelse för inskriften.
          type: string
          nullable: true
          example: Vikingatid
        material:
          $ref: '#/components/schemas/RunicMaterial'
        carver:
          description: Anger vem som ristat inskriften.
          type: string
          nullable: true
          example: 'Torsten (A) [Källström 2007a:269]'
        profile_style:
          description: Anger med vilken profilstil som inskriftsbäraren är ristad. Används bara om inskriftsbäraren är en runsten.
          type: array
          items:
            $ref: '#/components/schemas/ProfileStyle'
        nmr_identifiers:
          description: Identifierare för objekt som motsvarar inskriftsbäraren i andra informationssystem (National Monument Registers).
          type: array
          items:
            $ref: '#/components/schemas/Nmr'
        notes:
          description: Fritextfält för beskrivning av inskriftsbäraren.
          type: array
          items:
            type: string
          example: Parsten till Sö 35.
        runic_texts:
          description: Array of translations of the runicinscription.
          type: array
          items:
            $ref: '#/components/schemas/RunicText'
        ornamental:
          description: Anger huruvida objektet är ornamentantalt eller ej. Om sant - så finns inga runor, bara ornament.
          type: boolean
          example: true
        image_links:
          description: Innehåller array av URL:er till bilder av objektet. Url:erna finns lagrade i SRD databas och skördas ej till K-samsök.
          type: array
          items:
            type: string
          example:
            - >-
              http://kmb.raa.se/cocoon/bild/raa-image/16000300012834/normal/1.jpg
        references:
          description: Innehåller array av referenser till objektet. Referenserna finns lagrade i SRD databas och skördas ej till K-samsök.
          type: array
          items:
            type: string
          example:
            - 'Fv 1975:170'
            - 'http://fornvannen.se/pdf/1970talet/1975_166.pdf'
            - 'Andersson 1998b'

    RunicInscriptionIndex:
      description: Objektrepresentation av ett sökresultat från en s.k. 'Enkel sökning' efter signum.
        Objektet består endast av s.k. signifikanta attribut.
      type: object
      properties:
        inscription_id:
          type: string
          format: uuid
          description: Anger identiteten (uuid) till runinskriften i SNRD.
          example: ccf0a7f9-1f4c-421f-a321-0e36daea43eb
        signum1:
          description: Anger den första identitetsdelen för runinskriften, s.k signum.
            Platsbaserad. Oftast landskapskoden där runstenen hittades. Sätts samman med attribut 'signum 2'
          type: string
          example: Öl
        signum2:
          description: Anger den andra identitetssdelen för runinskriften, s.k signum.
            Anger oftast runinskriftens numrering inom platsbaserade delen. Sätts samman med attribut 'signum 1'
          type: string
          example: 10
        provenance:
          $ref: '#/components/schemas/Provenance'
        runic_texts:
          description: Array of translations of the runicinscription.
          type: array
          items:
            $ref: '#/components/schemas/RunicText'

    RunicMaterial:
      type: object
      properties:
        material_free_text:
          nullable: true
          description: Fritextfält som anger det material som inskriftsbäraren består av. Fältet är ostrukturerat.
          type: string
          example: granit
        materials:
          description: Array över de material som inskriftsbäraren består av. En inskriftsbärare kan bestå av flera material.
            Attributet är en strukturerad representation av attributet 'material_fritext' ovan.
          type: array
          items:
            $ref: '#/components/schemas/Material'

    RunicText:
      type: object
      description: Objektrepresentation av en inskriftsversion.
      properties:
        reading:
          description: Anger läsningen av texten
          type: string
          example: '...-abi · þaiR --tu · raisa · stein- · eftiR · rantui · moþor sina'
        reference:
          description: Anger bokstav som identifierar vilken alternativ tolkning olika runologer har haft.
          type: string
          nullable: true
          example: 'P'
        interpretations:
          description: Array av runinskriftens tolkningar. "Snygga till stavningen".
          type: array
          items:
            $ref: '#/components/schemas/Interpretation'
        translations:
          description: Array av runinskriftens översättningar.
          type: array
          items:
            $ref: '#/components/schemas/Translation'

    RunicTextTranslationType:
      required:
        - id
        - is_complete
        - method
        - name
        - proper_name_searchable
      type: object
      description: Översättningstyp, transliterering/normalisering/översättning av en runtext.
      properties:
        id:
          description: Anger identiteten (uuid) för översättningstypen.
          type: string
          example: da0b20c8-e036-456b-8f0a-6aeb06105f9a
        name:
          description: Namn på översättningstypen
          type: string
          example: Fornvästnordiska
        proper_name_searchable:
          description: Anger om texter av denna översättningstyp har sökbara egennamn
          type: boolean
          example: true
        is_complete:
          description: Anger om texter av denna översättningstyp är kompletta
          type: boolean
          example: true
        method:
          description: Anger översättningsmetod
          type: string
          example: NORMALISERING
          enum:
            - NORMALISERING
            - TRANSLITERERING
            - OVERSATTNING

    RunicInscriptionGeoPosition:
      description: Objektrepresentation av en inskriftsbärares geografiska positioner med nuvarande och ev. ursprungligt läge att rendera på en bakgrundskarta
      type: object
      properties:
#        current:
#          # Anger inskriftsbärarens senaste kända (oftast nuvarande) position.
#          $ref: '#/components/schemas/Geometry'
        current:
          description: Anger inskriftsbärarens senaste kända (oftast nuvarande) position. Notera att objektet kan vara null om positionen saknas!
          nullable: true
          allOf:
            - $ref: '#/components/schemas/Geometry'
        oldest_known:
          # Anger inskriftsbärarens äldsta kända position
          $ref: '#/components/schemas/Geometry'

    MapIndex:
      description: Objektrepresentation i "index" format av en inskriftsbärares signifikanta attribut.
        Innehåller geografiska positioner med nuvarande och ev. ursprungligt läge att rendera på en bakgrundskarta.
      type: object
      properties:
        inscription_id:
          description: Anger identiteten (uuid) till runinskriften.
          type: string
          format: uuid
          example: ccf0a7f9-1f4c-421f-a321-0e36daea43eb
        uri:
          description: Anger persistent identitet (uri) för runinskriften.
          type: string
          example: http://kulturarvsdata.se/uu/srdb/7b70c89a-c191-4d73-4455fd5dd2a7
        signum:
          description: Anger ett komplett signum bestående av signum1 + signum2.
          type: string
          example: Öl 10
        parish:
          description: Anger ev. namn på socken där inskriftsbäraren hittades.
          type: string
          nullable: true
          example: Bro socken
        current:
          # Anger inskriftsbärarens senaste kända (oftast nuvarande) position
          $ref: '#/components/schemas/Geometry'
        oldest_known:
          # Anger inskriftsbärarens äldsta kända position
          $ref: '#/components/schemas/Geometry'

    PlaceResponse:
      description: Objektrepresentation av en plats (place) och runinskriftsidentiteter avsett för "typeahead" ändamål.
      type: object
      properties:
        place:
          description: Innehåller namn på plats.
          type: string
          example: "Resmo kyrka"
        place_id:
          description: Anger identiteten (uuid) för platsen.
          type: string
          format: uuid
          example: ccf0a7f9-1f4c-421f-a321-0e36daea43eb

    RunicType:
      description: Anger vilka typer av runor som använts i inskriften.
      type: object
      properties:
        type:
          type: string
          description: Anger typ av runinskrift.
          nullable: true
          example: Skiffer
        category:
          type: string
          description: Anger kategori av runinskrift.
          nullable: true
          example: Spegelvända kvistrunor

    RunicTypeDescription:
      description: Anger fritextbeskrivning av de typer av runor som använts i inskriften.
      type: object
      properties:
        text:
          type: string
          nullable: true
          example: o-runan har dubbelsidig bistav
        language:
          type: string
          nullable: true
          example: sv-se

    SearchResult:
      required:
        - inscription
      type: object
      properties:
        inscription:
          type: array
          description: Runinskrifter
          items:
            $ref: '#/components/schemas/RunicInscription'
        found_words_index:
          type: array
          example:
            - 0
            - 4
            - 6
          items:
            type: integer
      description: Resultat av en sökfråga

    SearchQuery:
      description: Sökfråga som används för att sätta sökvillkor vid avancerad sökning i SRD
      required:
        - query
      type: object
      properties:
        query:
          type: array
          description: Textsökfråga
          items:
            $ref: '#/components/schemas/TextQueryGroup'
        timeinterval:
          description: Anger sökvillkor baserade på datering inom ett intervall.
          type: array
          items:
            $ref: '#/components/schemas/TimeInterval'
        year:
          description: Anger sökvillkor baserat på årtal.
          type: array
          items:
            $ref: '#/components/schemas/Year'
        filter:
          type: array
          description: Filtrering
          items:
            $ref: '#/components/schemas/Selection'

    SelectionGroup:
      description: Anger de möjliga urvalsgrupper som en avancerad sökning kan göras utifrån.
      required:
#        - id
        - name
      type: object
      properties:
#        id:
#          description: Anger identiteten för urvalsgruppen
#          type: string
#          example: b86b72cb-bc22-45fc-90cb-eaf213d3aaf9
        name:
          description: Anger logiskt namn på urvalsgruppen.
          type: string
          enum:
            - LAND
            - LANDSKAP
            - HARAD
            - SOCKEN
            - LAN
            - KOMMUN
            - FOREMAL
            - RUNOLOGISK_PERIOD
            - PROFILSTIL
            - RISTARE
            - BRAKTEATTYP
          example: SOCKEN

    SelectionItem:
      description: Anger ett urval (t ex socken Bro).
      required:
        - id
        - name
        - hasChildren
      type: object
      properties:
        id:
          type: string
          description: Anger identiteten (uuid) för urvalet
          example: c387aad1-9b4b-4c8c-ad0d-0bb4eaf605d6
        name:
          type: string
          description: Anger namnet på urvalet (lämpligt för presentation).
          example: Bro (Gotland)
        hasChildren:
          description: Anger om urvalsgruppen har ytterligare djup eller ej. True innebär att det finns ytterligare underliggande nivåer.
            Dessa attribut kan då undersökas vidare.
          type: boolean
          example: true

    Selection:
      description: Kompletterande filter med urvalsgrupper
      required:
        - item
        - op
      type: object
      properties:
        op:
          type: string
          description: Logisk operator att användas när filter kombineras
          enum:
            - AND
            - OR
            - NOT
        item:
          $ref: '#/components/schemas/SelectionItem'

    Signum:
      description: Objektrepresentation av signum och runinskriftsidentiteter avsett för "typeahead" ändamål.
      type: object
      properties:
        signum:
          description: Innehåller ett sammansatt signum bestående av signum 1 och signum 2.
          type: string
          example: "Öl 10"
        inscription_id:
          description: Anger identiteten (uuid) till runinskriften.
          type: string
          format: uuid
          example: ccf0a7f9-1f4c-421f-a321-0e36daea43eb

    TextQueryGroup:
      required:
        - condition
      type: object
      properties:
        op:
          type: string
          description: Anger logisk operator för användas när flera sökfrågor kombineras.
            Första frågan i en TextQueryGroup behöver inte ha en logisk operator
          enum:
            - AND
            - OR
            - NOT
        condition:
          type: array
          items:
            $ref: '#/components/schemas/TextQuery'
      description: Gruppering (tänk parenteser) av sökvillkor i en avancerad sökfråga

    TextQuery:
      required:
        - matching_text
        - proper_name_search
      type: object
      properties:
        op:
          type: string
          description: Anger logisk operator för användas när flera sökfrågor kombineras.
            Första frågan i en TextQuery behöver inte ha en logisk operator
          enum:
            - AND
            - OR
            - NOT
        matching_text:
          type: string
          description: Söktext
          example: þaiR
        proper_name_search:
          type: string
          description: Anger hur/om sökning skall ske i egennamn
          enum:
            - INCLUDE
            - EXCLUDE
            - ONLY
        translation_type_id:
          type: string
          description: Anger i vilken översättning sökningen skall ske
          example: da0b20c8-e036-456b-8f0a-6aeb06105f9a
      description: Sökfråga som används för att sätta villkor för textsökning i SRD

    Year:
      description: Anger årtal för att kunna uttrycka frågor av typen "sök runinskrifter daterade till år 1066".
      required:
        - year
      type: object
      properties:
        op:
          type: string
          description: Anger logisk operator för användas när flera sökfrågor kombineras.
            Första frågan i en TextQuery behöver inte ha en logisk operator
          enum:
            - AND
            - OR
            - NOT
        year:
          type: integer
          description: Anger årtalet.
          minLength: 1
          maxLength: 4
          example: 1066

    TimeInterval:
      description: Anger årtalsbaserat intervall för att kunna uttrycka frågor av typen "sök runinskrifter daterade inom intervallet år 800-900".
      required:
        - from_year
        - to_year
      type: object
      properties:
        op:
          type: string
          description: Anger logisk operator för användas när flera sökfrågor kombineras.
            Första frågan i en TextQuery behöver inte ha en logisk operator
          enum:
            - AND
            - OR
            - NOT
        from_year:
          type: integer
          description: Anger start årtal för intervallet. Angivet årtal inkluderas i sökningen.
          minLength: 1
          maxLength: 4
          example: 800
        to_year:
          type: integer
          description: Anger slut årtal för intervallet. Angivet årtal inkluderas i sökningen.
          minLength: 1
          maxLength: 4
          example: 900

    Translation:
      type: object
      description: Objektrepresentation av en översättning.
      properties:
        translation:
          description: Anger ev. översättning av texten
          type: string
          nullable: true
          example: Bengt raised this stone...
        language:
          description: Anger språket som översättningen är uttryckt i.
          type: string
          nullable: true
          example: Engelska
